#!/bin/bash

############################################
# Update global bash.bashrc
############################################

if ! grep -Fxq "# begin hestiacp-devtools" "/etc/bash.bashrc";then

cat <<EOT >> /etc/bash.bashrc
# begin hestiacp-devtools
export PATH="\$HOME/.wp-cli:\$HOME/.composer:\$PATH"
# end hestiacp-devtools
EOT

fi

############################################
# Patch phppgadmin
############################################

wget -O /usr/share/phppgadmin/classes/database/Connection.php https://raw.githubusercontent.com/Steveorevo/phppgadmin/master/classes/database/Connection.php